### ISSUE TITLE
ODC with directional counters

### ISSUE THREAD

**Issue by tdurand** [balena-io-playground/opendatacam#1]
Hi !

I've seen your panel https://www.youtube.com/watch?v=eRgCHVX8I3I yesterday, very nice overview of OpenDataCam, awesome to see people using the stuff we built !

I just wanted to let you know that we are just releasing new features that might interest you: https://github.com/opendatacam/opendatacam/issues/184 , we have Directional counters built-in now and fixed some issues with bearings.

Also very interested in you deploying work with balena cloud, looks very promising and will add a pointer to it for people looking for some more industrial way of deploying things.

Thibault

**Comment by alanb128** [comment]
Hi Thibault,

Thanks for the update and for building such a great project!

We would be very interested in working together to get our setup PRd into your repo at some point. We're working on base images that have all the prerequisites/dependencies so it would be a single push command to get OpenDataCam running on the device.

Alan

**Comment by tdurand** [comment]
@alanb128 , great !!

We are also waiting for nvidia to [fix a bug](https://forums.developer.nvidia.com/t/compiling-darknet-in-l4t-base-r32-3-1-docker-image-get-error-cicc-not-found/113154) on the base image nvidia:l4t-base that prevent us to build darknet to be able to simplify the hacky docker image wrapper we have for jetsons. (see more: https://github.com/opendatacam/opendatacam/issues/178 )

Feel free to close this one, and keep in touch !
