### ISSUE TITLE
Update DB

### ISSUE THREAD

**Issue by willytrueba** [balena-io-playground/opendatacam#10]
Hi,

I'm testing your OpenDataCam version for Balena, and it's fantastic !! I have two Jetson Nano with Balena Cloud and I install it without problems or issues. It's great.

But I have a question, and I don't have any idea the steps to make it. I want to modify the server/db/DBManager.js file into the opendatacam directory, and I make it from Balena Terminal on Balena Cloud. But the changes are not working, and if I restart the OpenDataCam, my changes dissapears.

I don't know if I have to download a version from GIT of ODC project, modify and after update on Balena, and these changes will be download when reinstall the Balena Software? Can you light my steps?

Thanks

**Comment by alanb128** [comment]
Hi @willytrueba you are correct, if you want to modify this project, you'll need to [clone](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/cloning-a-repository-from-github/cloning-a-repository) or download this repository. Make your changes and then use the [balena CLI](https://www.balena.io/docs/learn/more/masterclasses/cli-masterclass/) to push your new release to your devices. 

In addition to the links above, here is a getting started guide that might be helpful: https://www.balena.io/docs/learn/getting-started/jetson-nano/nodejs/

If you run into any problems, don't hesitate to post questions on our forums: https://forums.balena.io
