### ISSUE TITLE
Jetson nano kit

### ISSUE THREAD

**Issue by geologic** [balena-io-playground/opendatacam#8]
Hi

I'm going to buy a jetson nano kit, do you think opendatacam will work on the 2Gb version or do i need the 4Gb version?
Apart from having less USB and displayport, the big difference between them is the 2Gb less RAM.

Thanks

**Comment by alanb128** [comment]
Hi @geologic That's a good question. It would be great if someone who already has a 2Gb Nano could test it out and let us know. I think that is the only way to know for sure. I should have one to test in the next week or two if you can wait.

**Comment by geologic** [comment]
Thanks Alan, 2Gb version is almost half price of the 4Gb version, so i can wait a couple of weeks for your test.

**Comment by alanb128** [comment]
@geologic I did test with a 2Gb Nano but unfortunately, current versions of balenaOS won't boot on the new 2GB board. There's an open issue for that here: https://github.com/balena-os/balena-jetson/issues/122
Once that is solved, I can test whether OpenDataCam will work. I'll try to test OpenDataCam without balenaOS and report back so at least we have some idea what to expect.

**Comment by geologic** [comment]
:( 
Just ordered the 2Gb version yesterday...
Well, let's wait that guys from balenaOS can fix it. If you make any progress with OpenDataCam on the 2Gb Nano, please let me know.

**Comment by alanb128** [comment]
The new balenaOS device type `jetson-nano-2gb-devkit` is available in balena-staging. (I would expect it to be in production in a few weeks.) I've added the necessary Dockerfile to this repo to run on the Jetson nano 2GB and it seems to work just fine, with the same frame rate as the original Nano.

**Comment by mrpher** [comment]
@alanb128 did you overcome this error on the 2GB?
```
26.01.21 20:55:11 (-0500)  opendatacam  (gst-plugin-scanner:120): GStreamer-WARNING **: 01:55:11.338: Failed to load plugin '/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnvcompositor.so': libgstbadvideo-1.0.so.0: cannot open shared object file: No such file or directory
26.01.21 20:55:11 (-0500)  opendatacam  
26.01.21 20:55:11 (-0500)  opendatacam  (gst-plugin-scanner:120): GStreamer-WARNING **: 01:55:11.452: Failed to load plugin '/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstnveglglessink.so': libwayland-egl.so.1: cannot open shared object file: No such file or directory
```
Was excited to test the same as you with the 2GB image in staging (https://github.com/balena-os/balena-jetson/issues/122), but I've tried the following file `video_input` values: file, usbcam, and raspberrycam with the same error above.  Assumed it was related to a misconfig in the Dockerfile, but can't tell.

**Comment by alanb128** [comment]
@mrpher I did not get those errors on the 2GB, everything worked as expected. I used the default config values with a Microsoft Lifecam USB camera. Do you get the same errors using a Jetson Nano 4GB all other things being equal?

**Comment by mrpher** [comment]
@alanb128 Only have the newer 2GB.  Had assumed those errors were limited only to the raspberrycam as somewhere its documented as a known problem.  But was surprised to receive with file and stream methods too. 🤷

**Comment by alanb128** [comment]
@mrpher I haven't tried the 2GB Nano with a file or stream but will soon. In the meantime, do you have a USB camera you can try? (You are correct that the Raspberry Pi cam is not yet supported in this implementation.)

**Comment by alanb128** [comment]
This has been tested and confirmed working on the 2GB Nano, so I'm closing this issue.
